server:
  port: 8184

logging:
  level:
    com.codeforchangeskill: DEBUG

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

    eureka:
      instance:
        prefer_-ip-address: true
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
