server:
  port: 8184

logging:
  level:
    com.codeforchangeskill: DEBUG
    org.springframework.cloud: DEBUG

spring:
  config :
    import : optional:configserver:http://localhost:9290

  application:
    name: OrderService

  datasource :
    url : jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username : root
    password : root@123
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa :
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate :
      ddl-auto : update
    profiles :
      active : git

